#!/usr/bin/env python3
"""Crossings and their sensitivity to every contested input -> crossovers.md."""
import sys, pathlib, io
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from fhcost.budget import Config, DEFAULT, WEEK_S
from fhcost import nisq, ftqc, classical, curves, hubbard
from fhcost.record import model_id

OUT = pathlib.Path(__file__).parent / "crossovers.md"
buf = io.StringIO()
W = buf.write


def row(cfg: Config, label: str) -> str:
    fow, wil = cfg.but(pl_model="fowler"), cfg.but(pl_model="willow")
    mpf = cfg.but(trotter_order_k=2)
    lo, hi = classical.band(cfg)["band"]
    if cfg.tmax_mode == "inv_m":
        # the causal cone is sub-lattice-spacing: a cluster expansion is exact at
        # a cost independent of m, so "largest m" stops being a question at all
        return (f"| {label} | unbounded | \u2014 | \u2014 | \u2014 | \u2014 | \u2014 | "
                f"n/a (classically free) |")
    ft6 = ftqc.max_m_surface(1e6, fow)
    xc = curves.crossing(lambda n: ftqc.max_m_surface(n, fow), hi)
    pec6 = nisq.max_m(1e6, cfg, "pec")
    cap = f"{lo:.2g}" if lo == hi else f"{lo:.0f}–{hi:.0f}"
    return (f"| {label} | {cap} | {pec6:.1f} | "
            f"{nisq.max_m(1e6, mpf, 'pec'):.0f} | {ftqc.max_m_star(1e6, cfg):.1f} | "
            f"{ft6:.0f} | {ftqc.max_m_surface(1e6, wil):.0f} | "
            f"{'never' if xc is None else f'{xc:.1e}'} |")


HDR = ("| variation | ED capacity | NISQ+PEC | +MPF-4 | STAR | FT (Fowler) | "
       "FT (Willow) | n: FT clears classical |\n|---|---|---|---|---|---|---|---|\n")

W("# Crossovers and sensitivity\n\n")
W(f"Model `{model_id()}` -- the same fingerprint the figure and `explorer.html`\n"
  f"carry. Differing ids mean differing models; do not compare across them.\n\n")
W("All entries are `m` at `n = 10^6` unless the column says otherwise, for one\n"
  "week of wall clock. Generated by `crossover_table.py`; every number comes from\n"
  "`fhcost/`. See `METHODS.md` for the formulas and citations.\n\n")
W("## Baseline\n\n" + HDR + row(DEFAULT, "**baseline**") + "\n\n")

W("## Sensitivity\n\nEach row changes ONE input from the baseline.\n\n" + HDR)
VARS = [
    (DEFAULT.but(p=1e-4), "p = 1e-4"),
    (DEFAULT.but(p=1e-5), "p = 1e-5"),
    (DEFAULT.but(p=3e-3), "p = 3e-3 (today)"),
    (DEFAULT.but(eps=0.01), "eps = 0.01"),
    # s_sig is INERT under the default signal_regime="curve" -- these rows were
    # identical to the baseline (second-pass review, additional checks). Vary
    # the parameters the curve actually uses, and give the fixed-signal
    # scenario its own rows where s_sig does bite.
    (DEFAULT.but(signal_regime="fixed", s_sig=0.03), "fixed s = 0.03 (weak)"),
    (DEFAULT.but(signal_regime="fixed", s_sig=0.3), "fixed s = 0.3 (strong)"),
    (DEFAULT.but(s_data_rel_unc=0.40), "signal data 40% uncertain"),
    (DEFAULT.but(s_abs_floor=0.05), "absolute floor 0.05"),
    (DEFAULT.but(signal_bound="envelope"), "envelope bound (superseded)"),
    (DEFAULT.but(budget_s=86400.0), "1 day"),
    (DEFAULT.but(budget_s=30 * 86400.0), "1 month"),
    (DEFAULT.but(v=4.0), "v = 4J (correlation front)"),
    (DEFAULT.but(tmax_mode="const", tmax_const=1.0), "t_max = 1 (fixed)"),
    (DEFAULT.but(tmax_mode="inv_m"), "t_max = 1/m (slide 1, literal)"),
    (DEFAULT.but(U_over_J=8.0), "U/J = 8"),
    (DEFAULT.but(U_over_J=0.0), "U/J = 0 (free fermions)"),
    (DEFAULT.but(trotter="empirical"), "empirical Trotter (÷5 steps)"),
    (DEFAULT.but(c_g=30.0), "c_g = 30 (pessimistic gates)"),
    (DEFAULT.but(encoding="jw"), "Jordan-Wigner everywhere"),
    (DEFAULT.but(ent_rate=0.3), "weakly entangled (ent=0.3)"),
    (DEFAULT.but(ent_rate=1.5), "strongly entangled (ent=1.5)"),
    (DEFAULT.but(ram_bytes=1e15), "1 PB data centre"),
    (DEFAULT.but(ram_bytes=100e15), "100 PB data centre"),
    (DEFAULT.but(t_round=240e-9), "240 ns code round"),
    (DEFAULT.but(star_kappa=0.0533), "STAR rotation error ÷10"),
    (DEFAULT.but(hwp_batch=16), "HWP batch 16 (low workspace)"),
    (DEFAULT.but(hwp_batch=64), "HWP batch 64"),
    (DEFAULT.but(hwp_batch=1), "no HWP (plain synthesis)"),
]
for cfg, lab in VARS:
    W(row(cfg, lab) + "\n")

W("\n## Architecture ledgers, field by field, at m = 64\n\n")
W("The same compiled circuit costed on both architectures (review #5, test 4).\n"
  "The shared rows agree by construction; the rows that differ are the real\n"
  "architectural trade, not a bookkeeping difference.\n\n")
W("| field | surface FT | Pinnacle | |\n|---|---:|---:|---|\n")
for _name, _a, _b, _why in ftqc.ledger_comparison(64.0, DEFAULT):
    def _f(x):
        return f"{x:.4g}" if isinstance(x, (int, float)) and not isinstance(x, bool) else str(x)
    W(f"| {_name} | {_f(_a)} | {_f(_b)} | {_why} |\n")

W("\n## What each extrapolation buys, at n = 1e6\n\n")
W("| strategy | m | which extrapolation |\n|---|---|---|\n")
lo, hi = classical.band(DEFAULT)["band"]
for name, m, tag in curves.extrapolation_table(1e6):
    flag = " **(clears classical)**" if m > hi else ""
    W(f"| {name.replace('  + ', '&nbsp;&nbsp;+ ')} | {m:.1f}{flag} | {tag} |\n")

W("\n## Headline readouts\n\n")
s = curves.summary()
W(f"- Classical band: **m = {lo:.0f}–{hi:.0f}** (ED floor {classical.ed_frontier()}, "
  f"tensor network at the optimistic entanglement density above that).\n")
W(f"- Mitigated NISQ saturates: m = {nisq.max_m(1e2, DEFAULT, 'pec'):.1f} at n = 1e2 -> "
  f"{nisq.max_m(1e12, DEFAULT, 'pec'):.1f} at n = 1e12. "
  f"**Ten decades of qubits buy {nisq.max_m(1e12, DEFAULT, 'pec')/nisq.max_m(1e2, DEFAULT, 'pec'):.2f}x in m.**\n")
W(f"- Neither NISQ+PEC nor STAR ever clears the estimated ED capacity at any n.\n")
W(f"- At U/J = 0 the capacity column is NOT exact diagonalisation: the observable is\n"
  f"  polynomial there, and the entry is a measured single-core free-fermion frontier\n"
  f"  ({classical.free_fermion_frontier(DEFAULT.but(U_over_J=0.0)):.2g} sites). No quantum arm comes within six orders of magnitude.\n")
W(f"- Surface-code FT clears it at n ~ {s['n_ft_clears_classical_hi']:.1e} (idealised p_L) "
  f"or n ~ {s['n_ft_willow_clears_hi']:.1e} (measured p_L).\n")
W(f"- Trotter-step extrapolation is the largest single lever: NISQ+PEC "
  f"{s['pec_at_1e6']:.0f} -> {s['pec_mpf_at_1e6']:.0f} at n = 1e6.\n")
W(f"- G_total ~ m^(9/4), so the mitigated-NISQ ceiling scales as (ln n / p)^(4/9), "
  f"and the shot-limited FT curve as n^(4/9).\n")

OUT.write_text(buf.getvalue())
print(f"wrote {OUT}")
print(buf.getvalue()[:1500])
