#!/usr/bin/env python3
"""Write the shared result record and stamp every consumer from it.

    python3 make_record.py            # regenerate
    python3 make_record.py --check    # exit 1 if any consumer is stale

Second-pass review finding #3: the Python package, `explorer.html`, `README.md`
and `METHODS.md` reported different numbers at the same nominal settings. They
had all been maintained by hand. Now `fhcost/` is the only model and everything
else is generated:

    fhcost/*.py  ->  RESULTS.json  ->  explorer.html  (constants + parity probes)
                                  ->  HEADLINES.md
                                  ->  README.md       (headline block)

`--check` is what makes this stick: it regenerates into memory and diffs, so a
model change that is not followed by a regeneration fails loudly instead of
leaving a stale number in a document.
"""
from __future__ import annotations
import json, math, pathlib, sys
from dataclasses import fields
from fhcost import record, hubbard, ftqc, curves, classical
from fhcost import platform as _plat
from fhcost.budget import DEFAULT
from fhcost.presets import PRESETS

BEGIN = "/* ===== BEGIN GENERATED by make_record.py -- do not hand-edit ===== */"
END   = "/* ===== END GENERATED ===== */"
MD_BEGIN = "<!-- BEGIN GENERATED by make_record.py -- do not hand-edit -->"
MD_END   = "<!-- END GENERATED -->"

# The explorer re-runs these variants in the browser. Keeping the list short
# keeps the page responsive; keeping it MORE than one variant is what makes the
# check meaningful, since a single operating point is easy to match by accident.
JS_VARIANTS = ("default", "p_1e-4", "eps_0.01", "tmax_const", "mpf_k3",
               "trotter_bound", "u8", "u0", "arch_comparison",
               "helios", "neutral_atom", "two_layer_sc")


def js(x) -> str:
    """Python value -> JavaScript literal, with JS number formatting."""
    if isinstance(x, bool):
        return "true" if x else "false"
    if x is None:
        return "null"
    if isinstance(x, float):
        if not math.isfinite(x):
            return "null"
        if x == int(x) and abs(x) < 1e15:
            return str(int(x))
        return repr(x)
    if isinstance(x, int):
        return str(x)
    if isinstance(x, str):
        return json.dumps(x)
    if isinstance(x, (list, tuple)):
        return "[" + ",".join(js(v) for v in x) + "]"
    if isinstance(x, dict):
        return "{" + ",".join(f"{json.dumps(str(k))}:{js(v)}" for k, v in x.items()) + "}"
    raise TypeError(type(x))


def generated_block(rec: dict) -> str:
    cfg0 = {k: v for k, v in rec["config"].items()}
    presets = {name: {f.name: getattr(c, f.name) for f in fields(c)
                      if getattr(c, f.name) != getattr(DEFAULT, f.name)}
               for name, c in PRESETS.items()}
    w_meas = [[u, [[t, hubbard.W_MEASURED[u][t]] for t in sorted(hubbard.W_MEASURED[u])]]
              for u in sorted(hubbard.W_MEASURED)]
    w_mpf = [[o, [[t, hubbard.W_MPF[o][t]] for t in sorted(hubbard.W_MPF[o])]]
             for o in sorted(hubbard.W_MPF)]
    parity = {"variants": {k: rec["variants"][k] for k in JS_VARIANTS
                           if k in rec["variants"]}}
    L = [BEGIN,
         "// Every constant below comes straight out of fhcost/. Editing one here",
         "// does not change the model -- it only breaks the parity check.",
         f'const MODEL_ID = {js(rec["model_id"])};',
         "// the multiproduct order the dashed arm uses, from fhcost.curves",
         f"const MPF_ORDER = {js(curves.MPF_ORDER)};",
         f"const MAX_ASPECT = {js(curves.MAX_ASPECT)};",
         f"const CFG0 = {js(cfg0)};",
         f"const PRESETS = {js(presets)};",
         "// published |C^zz| (TFLO+GPR, Zenodo 17799843): [[U/J, [[t, s]...]]...]",
         f"const SIGNAL_DATA = {js([[u, [list(r) for r in rows]] for u, rows in sorted(hubbard.SIGNAL_DATA.items())])};",
         f"const SIGNAL_DATA_RANGE = {js(list(hubbard.SIGNAL_DATA_RANGE))};",
         "// measured second-order Trotter coefficient: [[U/J, [[tau, W]...]]...]",
         f"const W_MEASURED = {js(w_meas)};",
         "// measured MULTIPRODUCT coefficients, calibrated only to tau <= 0.5",
         f"const W_MPF = {js(w_mpf)};",
         f"const W_MPF_TAU_MAX = {js(hubbard.W_MPF_TAU_MAX)};",
         "// generalised bicycle codes [n, k, d, cycles/logical cycle, qubits/block]",
         f"const GB_CODES = {js([list(x) for x in ftqc.GB_CODES])};",
         "// Pinnacle magic engines, their Eqs. (7)-(10):",
         "// [p_phys, p_out, qubits, reject rate, d_a, r]",
         f"const PIN_ENGINE_TABLE = {js([list(x) for x in ftqc.PIN_ENGINE_TABLE])};",
         f"const PIN_REACTION_CYCLES = {js(ftqc.PIN_REACTION_CYCLES)};",
         "// hardware platforms, from published specs -- see refs/README.md:",
         "// [name, connectivity, t_2q, t_meas, t_round, n_parallel_2q,",
         "//  t_layer (null = derive), p_2q, n_demonstrated]",
         f"const PLATFORMS = {js({k: [v.name, v.connectivity, v.t_2q, v.t_meas, v.t_round, (None if v.n_parallel_2q == float('inf') else v.n_parallel_2q), v.t_layer, v.p_2q, v.n_demonstrated] for k, v in _plat.PLATFORMS.items()})};",
         f"const ADMITS = {js({k: sorted(v) for k, v in _plat.ADMITS.items()})};",
         f"const PINNACLE_PLATFORM = {js(curves.PINNACLE_PLATFORM)};",
         "// U = 0 free-fermion estimator: MEASURED single-core cost, validated",
         "// to 1.7e-15 against exact many-body evolution",
         f"const FF_SECONDS_PER_SITE = {js(classical.FF_SECONDS_PER_SITE)};",
         f"const FF_BYTES_PER_SITE = {js(classical.FF_BYTES_PER_SITE)};",
         "// published magic-state operating points, NOT a formula:",
         "// [name, p_phys, p_out, qubits, cycles per accepted state, family]",
         f"const MAGIC_SOURCES = {js([list(x) for x in ftqc.MAGIC_SOURCES])};",
         "// the Python answers this port must reproduce, intermediates included",
         f"const PARITY = {js(parity)};",
         END]
    return "\n".join(L)


def splice(text: str, block: str, begin: str, end: str, placeholder: str) -> str:
    if placeholder in text:
        return text.replace(placeholder, block)
    i, j = text.index(begin), text.index(end) + len(end)
    return text[:i] + block + text[j:]


def headline_lines(rec: dict) -> list[str]:
    """The prose numbers. Sourced from the record, never recomputed."""
    from fhcost import nisq, classical, curves, converged
    D = DEFAULT
    d = rec["variants"]["default"]
    lo, hi = d["classical_band"]
    r6 = d["reach"]["1e+06"]
    r3, r8 = d["reach"]["1000"], d["reach"]["1e+08"]
    s = curves.summary()
    L = [f"- Model `{rec['model_id']}`. Every number below is read out of "
         f"`RESULTS.json`; regenerate with `python3 make_record.py`.",
         f"- Classical (ED) frontier: **m = {lo:.0f}-{hi:.0f}**, an estimated capacity of "
         f"specified methods, not an impossibility boundary. The tensor-network arm is "
         f"unbounded by available data (`OPEN_ITEMS.md` O10).",
         f"- Mitigated NISQ saturates: m = {r3['nisq_pec']:.1f} at n = 10^3 to "
         f"{r8['nisq_pec']:.1f} at n = 10^8 -- **5 decades of qubits buy "
         f"{r8['nisq_pec'] / max(r3['nisq_pec'], 1e-9):.2f}x in m.**",
         f"- At n = 10^6: NISQ+PEC {r6['nisq_pec']:.0f}, STAR {r6['star']:.0f}, "
         f"surface FT {r6['surface']:.0f}, Pinnacle {r6['pinnacle']:.0f} -- but "
         f"Pinnacle is costed on a chip with TWO COUPLER LAYERS, which its "
         f"generalised bicycle codes require and the slide's nearest-neighbour "
         f"grid does not provide. On that grid it is "
         f"{r6['pinnacle_on_grid']:.0f}: not small, unavailable.",
         f"- Clearing the ED frontier: "
         f"Pinnacle {curves.fmt_crossing(s['n_pinnacle_clears_classical_hi'])}, "
         f"STAR {curves.fmt_crossing(s['n_star_clears_classical_hi'])}, "
         f"NISQ+PEC {curves.fmt_crossing(s['n_pec_clears_classical_hi'])}, "
         f"surface FT {curves.fmt_crossing(s['n_ft_clears_classical_hi'])}.",
         f"- Continuous m is a capacity proxy, and not every integer lattice can "
         f"hold the state: half filling at S^z_tot = 0 with one holon, one "
         f"doublon and a perfect triplet covering needs an EVEN site count, so "
         f"floor(sqrt(m)) can name a lattice that does not exist. At n = 10^6 "
         f"the largest admissible lattices are NISQ "
         f"{curves.fmt_lattice(r6['nisq_pec'])}, STAR "
         f"{curves.fmt_lattice(r6['star'])}, FT "
         f"{curves.fmt_lattice(r6['surface'])}, Pinnacle "
         f"{curves.fmt_lattice(r6['pinnacle'])} "
         f"(aspect capped at {curves.MAX_ASPECT:.0f}; beyond that a ribbon is "
         f"quasi-1D)."]
    pe = rec["variants"]["trotter_bound"]["reach"]["1e+06"]["nisq_pec"]
    L.append("- Trotter: under the commutator bound mitigated NISQ does not reach even a"
             f" 2x2 lattice; under the exact-diagonalisation calibration it reaches"
             f" {r6['nisq_pec']:.0f}. Curves are drawn as a band between the two."
             if not pe else
             f"- Trotter: the commutator bound is {r6['nisq_pec'] / pe:.1f}x conservative"
             " in m against the exact-diagonalisation calibration; curves are drawn as a"
             " band between them.")
    # Certification is SELF-CONSISTENT: an arm reaching m evolves to t_max(m) and
    # must then hold m_certified(t_max(m)) sites. At t_max = sqrt(m)/v the
    # requirement grows faster than m, so no arm on the figure closes the loop.
    best = max(r6["surface"], r6["pinnacle"], r6["star"], r6["nisq_pec"])
    need = converged.m_certified(hubbard.t_max(max(best, 1.0), D), D)
    L.append(f"- Converged answers: at t_max = sqrt(m)/v the Lieb-Robinson buffer is "
             f"self-defeating -- the best arm at n = 10^6 reaches m = {best:.0f}, whose "
             f"own t_max = {hubbard.t_max(max(best, 1.0), D):.2f} would need "
             f"m >= {need:.0f} to CERTIFY a thermodynamic-limit answer. Nothing on the "
             f"figure closes that loop, classical included. A bound failing is not "
             f"proof of non-convergence (`OPEN_ITEMS.md` O8).")
    L.append(f"- Error ledger sums to {hubbard.error_ledger(D)['TOTAL']:.2f} of the "
             f"tolerance, at per-time two-sided 95%.")
    return L


def render_all() -> dict[str, str]:
    """{path: new content} for every generated artefact."""
    rec = record.build()
    out = {"RESULTS.json": json.dumps(rec, indent=1) + "\n"}

    exp = pathlib.Path("explorer.html").read_text()
    out["explorer.html"] = splice(exp, generated_block(rec), BEGIN, END, "@@GENERATED@@")

    head = "\n".join(headline_lines(rec)) + "\n"
    out["HEADLINES.md"] = (
        "# Headline numbers (generated)\n\n"
        "Produced by `make_record.py` from `RESULTS.json`. Do not hand-edit; do not\n"
        "quote figures elsewhere without regenerating.\n\n" + head)

    rd = pathlib.Path("README.md").read_text()
    block = MD_BEGIN + "\n" + head + MD_END
    if MD_BEGIN in rd:
        i, j = rd.index(MD_BEGIN), rd.index(MD_END) + len(MD_END)
        out["README.md"] = rd[:i] + block + rd[j:]
    else:
        out["README.md"] = rd.rstrip() + "\n\n" + block + "\n"
    return out


def main(argv: list[str]) -> int:
    new = render_all()
    if "--check" in argv:
        stale = [p for p, txt in new.items()
                 if not pathlib.Path(p).exists()
                 or pathlib.Path(p).read_text() != txt]
        if stale:
            print("STALE, run `python3 make_record.py`:", ", ".join(sorted(stale)))
            return 1
        print(f"all artefacts current at model {record.model_id()}")
        return 0
    for p, txt in new.items():
        pathlib.Path(p).write_text(txt)
    print(f"model {record.model_id()}: wrote " + ", ".join(sorted(new)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
